### PR TITLE
Add .devcontainer for remote container

### PR DESCRIPTION
**Pull request by tom-tan**
This request adds support for remote container setting for VSCode.

### CODE REVIEW

**Comment by tom-tan** [comment]
# Tow to use

- Open the repository with remote container extension of VSCode
- run `sapporo` to start Sapporo service.
  - You can get the endpoint (http://localhost:8080/) in both of your host machine and in the dev container environment.
- When you update the code, you can restart Sapporo by:
  - kill the Sapporo process,
  - runn `python setup.py install` in `/workspace` and
  - re-run `sapporo`

**Comment by tom-tan** [comment]
Note: In the dev container with this change, `cwltool` does not work because it aborts without checking `DOCKER_HOST`.
After merging common-workflow-language/cwltool#1372 and building a container with the request, this problem will be solved.

**Comment by tom-tan** [comment]
Now common-workflow-language/cwltool#1372 was solved!
Once the container of cwltool with it is released, this request is ready for merge.

**Comment by suecharo** [comment]
@tom-tan 
I saw the statement that we don't need to include `.devcontainer` in git management.
What do you think?
Also, is it possible to separate the compose file as something else, like `docker-compose.dev-container.yml`?
I'm not sure if it's appropriate to merge to develop branch.

**Comment by tom-tan** [comment]
It is not the time to merge this request because the docker container for `cwltool` with common-workflow-language/cwltool#1372 is not available.

---

> I saw the statement that we don't need to include .devcontainer in git management.

It depends on what we want to provide in this repository.
IMO `.devcontainer` has a similar role with CI settings such as `.travis.yml` or `.github/workflows`.

- The files such as `.travis.yml` or `.github/workflows/ci.yml` provide CI infrastructures to developers.
  - Other developer can enable such settings by cloning the repository and by integrating it with corresponding CI services.
  - It is still possible to use other CI services such as CircleCI.
- `.devcontainer` provides a development infrastructure to developers.
  - It is still possible to use other development platforms such as Emacs, Vim, Atom etc.

For me, the question "do we need to include `.devcontainer` in the repository?" is same as the following: "do we need to provide a default development environment in the repository?"

> What do you think?

It is worth adding to the repository. It makes much easier to setup the development environment and therefore it makes easier for other developer to contribute this repository!


> Also, is it possible to separate the compose file as something else, like docker-compose.dev-container.yml?

Yes! We can fix `dockerComposeFile` in`.devcontainer/devcontainer.json` to refer `docker-compose.dev-container.yml`, for example.

**Pull request closed without merging**
